## Generic macro to find then load EG module details to global vars
macro(EG_LOAD_PACKAGE_DETAILS module)
	string(TOUPPER ${module} umodule)
	find_package(${module} REQUIRED)
	if (${umodule}_FOUND)
		include_directories(${${umodule}_INCLUDE_DIRS})
		set(LIB_DIRS "${LIB_DIRS};${${umodule}_LIB_DIR}")
		set(LIBS ${LIBS} ${${umodule}_LIBRARIES})
		set(DOXY_TAGFILES "${DOXY_TAGFILES} \"${${umodule}_DOC_DIR}/${${umodule}_NAME}.tag\"=\"${${umodule}_DOC_DIR}/html\"")
		#message(STATUS "********************")
		#message(STATUS "INC=${${umodule}_INCLUDE_DIRS}")
		#message(STATUS "LIBS=${LIBS}")
		#message(STATUS "LIB_DIRS=${LIB_DIRS}")
		#message(STATUS "DOXY_TAGFILES=${DOXY_TAGFILES}")
		#message(STATUS "********************")
	else()
		message(FATAL_ERROR "Failed to find ${umodule}")
	endif()
endmacro(EG_LOAD_PACKAGE_DETAILS)

