project(egcore C)

set(PROJECT_BRIEF "EGCORE ANSI C library.")

set(${PROJECT_NAME}_MAJOR_VERSION 1)
set(${PROJECT_NAME}_MINOR_VERSION 1)
set(${PROJECT_NAME}_PATCH_VERSION 1)
set(${PROJECT_NAME}_TWEAK_VERSION )

set(PROJECT_PACKAGE_DEPENDENCIES_DEBIAN "libxml2 (>= 2.7.6), libcurl3 (>= 7.16.2-1)")

