#ifndef __@PROJECT_NAME_UPPER@_VERSION_H__
#define __@PROJECT_NAME_UPPER@_VERSION_H__

#define @PROJECT_NAME_UPPER@_COPYRIGHT "@PROJECT_COPYRIGHT@"

#define @PROJECT_NAME_UPPER@_VERSION "@PROJECT_VERSION@"

#define @PROJECT_NAME_UPPER@_VERSION_MAJOR @PROJECT_MAJOR_VERSION@
#define @PROJECT_NAME_UPPER@_VERSION_MINOR @PROJECT_MINOR_VERSION@
#define @PROJECT_NAME_UPPER@_VERSION_PATCH @PROJECT_PATCH_VERSION@
#define @PROJECT_NAME_UPPER@_VERSION_TWEAK @PROJECT_TWEAK_VERSION@

// The format of this varies across platforms:
// "UNIX: <output of date -utc>"
// "WIN: <output of date /t> <output of time /t>"
// "XXX: 000000" 
#define @PROJECT_NAME_UPPER@_TIMESTAMP "@PROJECT_TIMESTAMP@"

#endif /* __@PROJECT_NAME_UPPER@_VERSION_H__ */
